---
extends:
  - xo
  - xo-typescript
  - plugin:unicorn/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:solid/typescript
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended

settings:
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project:
        - tsconfig.json
        - tsconfig.node.json
    node: true
  import/external-module-folders:
    - .yarn

rules:
  max-params: 0
  "@typescript-eslint/naming-convention": 0
  unicorn/filename-case:
    - error
    - cases:
        kebabCase: true
        pascalCase: true
  "@typescript-eslint/prefer-nullish-coalescing": 0
  unicorn/prevent-abbreviations: 0
  jsx-a11y/label-has-associated-control: 0
parserOptions:
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
