---
extends:
  - xo
  - xo-typescript
  - plugin:unicorn/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:solid/typescript
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended

settings:
  import/resolver:
    typescript: true
    node: true
  import/external-module-folders:
    - .yarn
