---
extends:
  - xo
  - xo-typescript
  - plugin:unicorn/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:solid/typescript
  - plugin:jsx-a11y/recommended
  - plugin:prettier/recommended

settings:
  import/resolver:
    typescript: true
    node: true
  import/external-module-folders:
    - .yarn

rules:
  max-params: 0
  "@typescript-eslint/naming-convention":
    - error
    - selector: default
      format:
        - strictCamelCase
      leadingUnderscore: allow
      trailingUnderscore: allow
    - selector: import
      format:
        - camelCase
        - StrictPascalCase
    - selector: variable
      format:
        - camelCase
        - UPPER_CASE
      leadingUnderscore: allow
      trailingUnderscore: allow
    - selector: typeLike
      format:
        - StrictPascalCase
    - selector:
        - objectLiteralProperty
        - typeProperty
      format:
        - snake_case
        - strictCamelCase
      leadingUnderscore: allow
      trailingUnderscore: allow
    - selector: function
      format:
        - strictCamelCase
        - StrictPascalCase
    - selector: enumMember
      format:
        - StrictPascalCase
  unicorn/filename-case:
    - error
    - cases:
        kebabCase: true
        pascalCase: true
  "@typescript-eslint/prefer-nullish-coalescing": 0
parserOptions:
  project:
    - ./tsconfig.json
    - ./tsconfig.node.json
